services:
  qemu:
    container_name: dos-win31
    image: albrechtloh/qemu-dos-win31:latest
    #image: "dos-win31-docker-arm64"

    environment:
      DEBUG: "y"

    ports:
      # Port 8006 is console tty web VNC
      - 8006:8006

    stop_grace_period: 2m
    restart: on-failure
 
